### ISSUE TITLE
include example in READme

### ISSUE THREAD

**Issue by rohan999chaudhary** [aalok-sathe/pathin#1]
For example how does one 
> Most importantly, add /usr/local/texlive/2021/bin/x86_64-linux
to your PATH for current and future sessions.

using pathin

**Comment by aalok-sathe** [comment]
good question!

**first**, you would configure `pathin` if you haven't already:
```bash
    pathin configure
```

**second**, you would add the path you mentioned using pathin
```bash
    pathin add --directory /usr/local/texlive/2021/bin/x86_64-linux
```

**finally**, you would close the current terminal window and open a new session for the path to be recognized. in your case, since TexLive will likely be needed by other programs such as a LaTeX editor, you would need to *log out* and *log back in* for this to take effect.
